language: c
dist: bionic
services:
 - docker
before_install:
 - docker build -t spk121/mlg-lib .

script: docker run spk121/mlg-lib /bin/sh -c "cd /app; autoreconf -vif && ./configure && make -j4 distcheck"
