\input texinfo
@settitle RyuLib

@copying
Copyright @copyright{} 2017 Mike Gran
@end copying

@titlepage
@title Ryulib
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@c Output the table of the contents at the beginning.
@contents

@ifnottex
@node Top, The MLG utilities library, (dir), (dir)

@top Ryulib

This manual is for Ryulib.
@end ifnottex

@menu
* The MLG utilities library::
* mlg utils::
* C procedures::
* Index::                       Complete index.


@end menu

@node The MLG utilities library, mlg utils, Top, Top
@chapter The MLG utilities library

Every programmer has a list of library routines that they use often.
These are mine.  The @code{(mlg)} library is routines that seem somewhat
basic but are not in the standard library.

@node mlg utils, C procedures, The MLG utilities library, Top
@chapter mlg utils

The bulk of this module is procedures that search for special directory
locations, plus a couple of other random bits.

@deffn Procedure search-path-separator-string
This returns ``;'' on Windows or ``:'' otherwise.  This string is the
conventionally used separator in lists of paths, such as
@example
/usr/local/share:/usr/share
@end example
@end deffn

@deffn Procedure get-system-data-dirs
Returns the preference-ordered set of base directores to search for
data files.  This does not include the user's data directory.  The
return is a list of strings of directory names.
@end deffn

@deffn Procecure find-data-file filename
Searches for a file named @var{filename} in the user's data directory
and the system data directories.  @var{filename} may be a relative path
like @code{path/fname}. The directories are searched in preference
order: the user's data directory is searched, then the system data
directories.  The first matching filepath is returned as a string.  If
no matching file is found, @code{#f} is returns.

This procedure does not recursively search subdirectories.
@end deffn

@node C procedures, Index, mlg utils, Top
@chapter The Ryu C-like procedures library

This is a library of procedure that are intentionally similar to C
procedures.  This library is partly a dumb joke and partly a useful
utility to make porting from C easier.

@defun Macro assert condition
Given @var{condition}, if @var{condition} evaluates to @code{#f},
this raises an error with key @code{'misc-error} and a message
constructed by displaying @var{condition}.

If there is a variable in scope named @code{NDEBUG} which is
not @code{#f}, this macro does nothing.
@end defun

Note that there is also a more expansive assertion macro in
@code{(rnrs base)} but it throws the sometimes-more-awkward R6RS
exception.

@cindex index entry, another

Here is a numbered list.

@enumerate
@item
This is the first item.

@item
This is the second item.
@end enumerate

@node Index,  , C procedures, Top
@unnumbered Index

@printindex cp

@bye


